name: Node-js-password-generator CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.15.1

      - name: Install dependencies
        run: npm install

      - name: Run Test
        run: npm test

      - name: Build project
        run: npm run build

      - name: Compile frontend script
        run: npm run compile-client

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: password-generator
          path: |
            dist/
            .gitignore
            package.json
            README.md
